"use client";

import { useState } from "react";
import { ArrowUp, Bot, ChevronDown, Sparkles, X } from "lucide-react";

export function ChatAssistant() {
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<{ from: "assistant" | "user"; text: string }[]>([{ from: "assistant", text: "I can look up stored spring records, recharge-zone records, or weather-source configuration. Results are decision support and need source review." }]);
  async function send() { const prompt = question.trim(); if (!prompt) return; setMessages(current => [...current, { from: "user", text: prompt }]); setQuestion(""); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000"}/api/assistant/query`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: prompt }) }); const result = await response.json(); setMessages(current => [...current, { from: "assistant", text: result.answer || "The data lookup did not return a response." }]); } catch { setMessages(current => [...current, { from: "assistant", text: "Unable to connect to the SpringVyra API. Start the backend and try again." }]); } }
  return <>{open && <section className="chat-panel"><header><div className="chat-head-icon"><Bot size={18}/></div><div><b>SpringVyra data assistant</b><span><i/> Controlled lookups · no write actions</span></div><button className="chat-close" onClick={()=>setOpen(false)} aria-label="Close assistant"><X size={17}/></button></header><div className="chat-intro"><span><Sparkles size={13}/> DATA LOOKUP PROTOTYPE</span><p>Ask about available records</p></div><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`chat-message ${m.from}`}>{m.from==="assistant"&&<span className="bot-avatar"><Bot size={14}/></span>}<p>{m.text}</p></div>)}</div><div className="chat-suggestions"><button onClick={()=>setQuestion("Show spring records")}>Spring records</button><button onClick={()=>setQuestion("Show recharge zones")}>Recharge zones</button></div><form className="chat-input" onSubmit={e=>{e.preventDefault();send();}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about stored data…"/><button aria-label="Send message"><ArrowUp size={17}/></button></form><small className="chat-note">Prototype lookup only · predictions need field validation.</small></section>}<button className={`chat-launcher ${open?"chat-open":""}`} onClick={()=>setOpen(!open)} aria-label={open?"Close assistant":"Open SpringVyra assistant"}>{open?<ChevronDown size={20}/>:<><span className="launcher-sparkle"><Sparkles size={14}/></span><span>Ask SpringVyra</span><span className="launcher-badge">DATA</span></>}</button></>;
}
