"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { FieldValidationForm } from "@/components/FieldValidationForm";
import { SpringManager } from "@/components/SpringManager";
import { DataSourcesModule, InterventionModule, MonitoringModule, RechargeModule, UnavailableModule } from "@/components/DecisionModules";
import { getCopy, languageNames, type Language } from "@/lib/i18n";
import type { Feature, Geometry } from "geojson";
import { Activity, AlertTriangle, ChevronDown, CircleHelp, Cloud, Database, Droplets, Download, FileText, Layers3, Leaf, MapPin, MoreHorizontal, Search, SlidersHorizontal, Sprout, Waves } from "lucide-react";

type Spring = { id: number; spring_code: string; name: string; spring_type: string; latitude: number; longitude: number; elevation: number; discharge_rate: number; water_quality_ph: number; status: string };
type ZoneFeature = Feature<Geometry, { zone_code: string; suitability_class: string; data_status: string }>;
type Data = { total_springs: number; active_springs: number; active_zones: number; average_suitability: number | null; model_confidence: number | null; data_status: string; springs: Spring[]; zones: ZoneFeature[] };
const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
const MapView = dynamic(() => import("./MapView"), { ssr: false, loading: () => <div className="map-loading"><span className="loader" />Loading watershed layers</div> });
const sample: Data = { total_springs: 8, active_springs: 6, active_zones: 4, average_suitability: null, model_confidence: null, data_status: "DEMO", zones: [], springs: [
  { id: 1, spring_code: "NG-001", name: "Jal Dhara", spring_type: "Hillslope", latitude: 30.1264, longitude: 78.312, elevation: 1840, discharge_rate: .42, water_quality_ph: 7.1, status: "active" }, { id: 2, spring_code: "NG-002", name: "Banshi Gad", spring_type: "Fracture", latitude: 30.1432, longitude: 78.3395, elevation: 2115, discharge_rate: .28, water_quality_ph: 6.8, status: "active" }, { id: 3, spring_code: "NG-003", name: "Kaphal Pani", spring_type: "Depression", latitude: 30.1088, longitude: 78.3654, elevation: 1670, discharge_rate: .63, water_quality_ph: 7.3, status: "active" }, { id: 4, spring_code: "NG-004", name: "Aama Naula", spring_type: "Contact", latitude: 30.163, longitude: 78.2891, elevation: 2260, discharge_rate: .19, water_quality_ph: 7, status: "seasonal" }, { id: 5, spring_code: "NG-005", name: "Buransh Source", spring_type: "Hillslope", latitude: 30.0902, longitude: 78.3258, elevation: 1535, discharge_rate: .51, water_quality_ph: 7.2, status: "active" }, { id: 6, spring_code: "NG-006", name: "Kwarik Khal", spring_type: "Fracture", latitude: 30.1774, longitude: 78.358, elevation: 2380, discharge_rate: .11, water_quality_ph: 6.9, status: "monitoring" }, { id: 7, spring_code: "NG-007", name: "Simal Srot", spring_type: "Depression", latitude: 30.1351, longitude: 78.275, elevation: 1980, discharge_rate: .34, water_quality_ph: 7.4, status: "active" }, { id: 8, spring_code: "NG-008", name: "Gwar Gaad", spring_type: "Contact", latitude: 30.0761, longitude: 78.3792, elevation: 1450, discharge_rate: .23, water_quality_ph: 6.7, status: "active" },
] };

function number(n: number) { return new Intl.NumberFormat("en-IN").format(n); }
export default function Dashboard() {
  const [data, setData] = useState<Data>(sample);
  const [live, setLive] = useState(false);
  const [view, setView] = useState("Overview");
  const [language, setLanguage] = useState<Language>("en");
  const t = getCopy(language);
  useEffect(() => { const saved = window.localStorage.getItem("springvyra-language") as Language | null; if (saved && saved in languageNames) setLanguage(saved); }, []);
  useEffect(() => { window.localStorage.setItem("springvyra-language", language); document.documentElement.lang = language; }, [language]);
  useEffect(() => { let active = true; const load = async () => { try { const r = await fetch(`${API}/api/dashboard`, { cache: "no-store" }); if (!r.ok) throw new Error(); const d = await r.json(); if (active) { setData({ ...sample, ...d, zones: d.zones || [] }); setLive(true); } } catch { if (active) { setData(sample); setLive(false); } } }; load(); const interval = window.setInterval(load, 30000); return () => { active = false; window.clearInterval(interval); }; }, []);
  const sourceLabel = !live ? t.apiUnavailable : data.data_status === "DEMO" ? t.apiConnected : data.data_status === "LATEST AVAILABLE" ? t.latestData : data.data_status || t.unverifiedData;
  const statCards = [
    { label: t.monitoredSprings, value: number(data.total_springs), change: data.data_status === "DEMO" ? t.demoRecords : t.storedRecords, icon: Droplets, tone: "mint", sub: `${data.active_springs} ${t.listedActive}` },
    { label: t.priorityZones, value: number(data.active_zones), change: data.data_status === "DEMO" ? t.demoRecords : t.storedRecords, icon: Layers3, tone: "gold", sub: t.noBoundaries },
    { label: t.meanSuitability, value: data.average_suitability == null ? "Not available" : `${data.average_suitability}%`, change: t.noValidatedAnalysis, icon: Sprout, tone: "sage", sub: t.sourcedGis },
    { label: t.modelConfidence, value: data.model_confidence == null ? "Not available" : `${Math.round(data.model_confidence * 100)}%`, change: t.confidenceAccuracy, icon: Activity, tone: "blue", sub: data.model_confidence == null ? t.noValidatedModel : t.seeProvenance },
  ];
  return <><div style={{ position: "fixed", top: 14, right: 18, zIndex: 20 }}><label className="language-picker"><span className="sr-only">Language</span><select value={language} onChange={event=>setLanguage(event.target.value as Language)} aria-label="Language"><option value="en">{languageNames.en}</option><option value="hi">{languageNames.hi}</option><option value="ne">{languageNames.ne}</option></select></label></div><main className="app-frame">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Waves size={21} strokeWidth={2.2}/></div><div><b>springvyra</b><span>WATERSHED INTELLIGENCE</span></div></div><div className="workspace-label">WORKSPACE <ChevronDown size={13}/></div><div className="workspace-card"><div className="workspace-icon">SV</div><div><b>Spring network</b><span>Configured study area</span></div><MoreHorizontal size={17}/></div><div className="nav-label">MONITOR</div><nav className="nav-list">{[{name:"Overview",icon:Activity},{name:"Map",icon:MapPin},{name:"Spring network",icon:Droplets},{name:"Recharge analysis",icon:Layers3},{name:"Intervention planning",icon:Sprout},{name:"Risk analysis",icon:AlertTriangle},{name:"Field observations",icon:Leaf},{name:"Monitoring",icon:Activity},{name:"Reports",icon:FileText},{name:"Data sources",icon:Database}].map(({name,icon:Icon})=><button key={name} className={`nav-item ${view===name?"selected":""}`} onClick={()=>setView(name)}><Icon size={17}/>{name}{name==="Spring network"&&<span className="nav-count">{data.total_springs.toString().padStart(2,"0")}</span>}</button>)}</nav><div className="nav-label tools-label">TOOLS</div><button className="nav-item" onClick={()=>setView("Catchment explorer")}><MapPin size={17}/>Catchment explorer</button><button className="nav-item" onClick={()=>setView("Weather data")}><Cloud size={17}/>Weather data</button><div className="sidebar-spacer"/><div className="season-card"><div className="season-top"><span className="season-dot"/>DATA READINESS</div><b>Sources required</b><p>Weather data source not configured.</p><small>Recharge analysis awaits sourced GIS inputs.</small></div><div className="user-card"><div className="avatar">SV</div><div><b>Local workspace</b><span>Authentication not configured</span></div><ChevronDown size={15}/></div></aside>
    <section className="main-column"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><i>/</i><b>{view}</b></div><div className="top-actions"><span className={`sync-state ${live&&data.data_status!=="DEMO"?"is-live":""}`}><span/> {sourceLabel}</span><button className="icon-button" aria-label="Search" disabled title="Location search is not implemented"><Search size={17}/></button><button className="help-button" disabled title="Help content is not configured"><CircleHelp size={16}/> Help centre</button><div className="top-avatar">SV</div></div></header>
    <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/>SPRING & GROUNDWATER MONITORING</div><h1>{view === "Overview" ? "Watershed overview" : view} <span className="wave">✳</span></h1><p>Monitor available records and check source readiness.</p></div><div className="heading-actions"><button className="secondary-button" disabled title="Report generation is not configured"><SlidersHorizontal size={15}/> Data sources</button><button className="primary-button" disabled title="Report generation is not configured"><Download size={15}/> Export unavailable</button></div></div>
    <div className="data-notice"><b>{sourceLabel}</b><span>Decision-support only. Predictions require sourced environmental data, field validation, and expert review.</span></div>
    {view === "Field observations" ? <FieldValidationForm/> : view === "Spring network" ? <SpringManager/> : view === "Recharge analysis" || view === "Recharge zones" ? <RechargeModule/> : view === "Intervention planning" ? <InterventionModule/> : view === "Monitoring" ? <MonitoringModule/> : view === "Data sources" ? <DataSourcesModule/> : view === "Risk analysis" ? <UnavailableModule title="Risk analysis" endpoint="/api/risk-analysis" icon={AlertTriangle}/> : view === "Weather data" ? <UnavailableModule title="Weather and rainfall" endpoint="/api/weather" icon={Cloud}/> : view === "Reports" ? <UnavailableModule title="Reports" endpoint="/api/reports/status" icon={FileText}/> : <>{view === "Catchment explorer" && <div className="module-notice"><b>Catchment explorer is not implemented in this prototype.</b><span>Catchment boundary data has not been supplied.</span></div>}<div className="stats-grid">{statCards.map(({label,value,change,icon:Icon,tone,sub})=><article className="stat-card" key={label}><div className="stat-head"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={17}/></span></div><div className="stat-value">{value}</div><div className="stat-foot"><span className="change">{change}</span><span className="stat-sub">{sub}</span></div></article>)}</div>
    <div className="section-heading"><div><h2>Watershed overview</h2><p>Map coverage depends on the locations supplied in the records</p></div><button className="period-button" disabled title="Date range filtering is not implemented">Date range unavailable</button></div>
    <section className="map-panel"><div className="map-toolbar"><div className="map-title"><span className="map-title-icon"><MapPin size={16}/></span><div><b>Spring & recharge map</b><small>Map extent follows supplied spring coordinates</small></div><span className={`map-live ${data.data_status === "DEMO" ? "demo" : ""}`}>{data.data_status === "DEMO" ? "DEMO DATA" : data.data_status}</span></div></div><div className="map-content"><MapView springs={data.springs} zones={data.zones}/><div className="map-legend"><b>MAP LEGEND</b><span><i className="legend-dot flowing"/>Spring coordinates</span><span><i className="legend-dot watch"/>Seasonal / monitoring</span><span><i className="legend-zone"/>{data.zones.length ? "Supplied zone geometry" : "No zone boundaries supplied"}</span></div></div><div className="map-summary"><div><Droplets size={15}/><span><b>{data.total_springs} spring records</b></span></div><div><Layers3 size={15}/><span><b>{data.active_zones} demo/recorded zone metrics</b></span></div><span className="map-updated">{sourceLabel}</span></div></section>
    <section className="inventory-section"><div className="inventory-heading"><div><h2>Spring inventory</h2><p>Stored records; verify provenance before interpreting measurements</p></div><button className="text-button" onClick={()=>setView("Spring network")}>View all springs <span>↗</span></button></div><div className="table-wrap"><table><thead><tr><th>SPRING</th><th>TYPE</th><th>ELEVATION</th><th>DISCHARGE</th><th>WATER PH</th><th>STATUS</th><th/></tr></thead><tbody>{data.springs.slice(0,5).map((s,i)=><tr key={s.id}><td><div className="spring-cell"><span className={`spring-mini mini-${i%4}`}><Droplets size={15}/></span><span><b>{s.name}</b><small>{s.spring_code} · {data.data_status}</small></span></div></td><td><span className="type-pill">{s.spring_type}</span></td><td>{number(s.elevation)} <span className="unit">m</span></td><td><b>{s.discharge_rate.toFixed(2)}</b> <span className="unit">L/s</span></td><td>{s.water_quality_ph.toFixed(1)}</td><td><span className={`status-pill ${s.status.toLowerCase()}`}><i/>{s.status}</span></td><td><button className="row-menu" aria-label="More options" disabled title="Row actions are not implemented"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></section></>}
    <footer><span>SpringVyra <b>·</b> Watershed intelligence for resilient mountain communities</span><span>Dashboard syncs every 30 sec <i/> <span>Data sources & methodology</span></span></footer></div></section>
  </main></>;
}
