"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, ChevronDown, CircleHelp, Cloud, Droplets, Download, Layers3, Leaf, MapPin, Menu, MoreHorizontal, Radio, Search, SlidersHorizontal, Sprout, Waves } from "lucide-react";

type Spring = { id: number; spring_code: string; name: string; spring_type: string; latitude: number; longitude: number; elevation: number; discharge_rate: number; water_quality_ph: number; status: string };
type Data = { total_springs: number; active_springs: number; active_zones: number; average_suitability: number; model_confidence: number; springs: Spring[] };
const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
const MapView = dynamic(() => import("./MapView"), { ssr: false, loading: () => <div className="map-loading"><span className="loader" />Loading watershed layers</div> });
const sample: Data = { total_springs: 8, active_springs: 6, active_zones: 4, average_suitability: 69, model_confidence: 83, springs: [
  { id: 1, spring_code: "NG-001", name: "Jal Dhara", spring_type: "Hillslope", latitude: 30.1264, longitude: 78.312, elevation: 1840, discharge_rate: .42, water_quality_ph: 7.1, status: "active" }, { id: 2, spring_code: "NG-002", name: "Banshi Gad", spring_type: "Fracture", latitude: 30.1432, longitude: 78.3395, elevation: 2115, discharge_rate: .28, water_quality_ph: 6.8, status: "active" }, { id: 3, spring_code: "NG-003", name: "Kaphal Pani", spring_type: "Depression", latitude: 30.1088, longitude: 78.3654, elevation: 1670, discharge_rate: .63, water_quality_ph: 7.3, status: "active" }, { id: 4, spring_code: "NG-004", name: "Aama Naula", spring_type: "Contact", latitude: 30.163, longitude: 78.2891, elevation: 2260, discharge_rate: .19, water_quality_ph: 7, status: "seasonal" }, { id: 5, spring_code: "NG-005", name: "Buransh Source", spring_type: "Hillslope", latitude: 30.0902, longitude: 78.3258, elevation: 1535, discharge_rate: .51, water_quality_ph: 7.2, status: "active" }, { id: 6, spring_code: "NG-006", name: "Kwarik Khal", spring_type: "Fracture", latitude: 30.1774, longitude: 78.358, elevation: 2380, discharge_rate: .11, water_quality_ph: 6.9, status: "monitoring" }, { id: 7, spring_code: "NG-007", name: "Simal Srot", spring_type: "Depression", latitude: 30.1351, longitude: 78.275, elevation: 1980, discharge_rate: .34, water_quality_ph: 7.4, status: "active" }, { id: 8, spring_code: "NG-008", name: "Gwar Gaad", spring_type: "Contact", latitude: 30.0761, longitude: 78.3792, elevation: 1450, discharge_rate: .23, water_quality_ph: 6.7, status: "active" },
] };

function number(n: number) { return new Intl.NumberFormat("en-IN").format(n); }
export default function Dashboard() {
  const [data, setData] = useState<Data>(sample);
  const [live, setLive] = useState(false);
  const [view, setView] = useState("Overview");
  useEffect(() => { let active = true; const load = async () => { try { const r = await fetch(`${API}/api/dashboard`, { cache: "no-store" }); if (!r.ok) throw new Error(); const d = await r.json(); if (active) { setData(d); setLive(true); } } catch { if (active) setLive(false); } }; load(); const interval = window.setInterval(load, 30000); return () => { active = false; window.clearInterval(interval); }; }, []);
  const statCards = [
    { label: "Monitored springs", value: number(data.total_springs), change: "+2 this month", good: true, icon: Droplets, tone: "mint", sub: `${data.active_springs} flowing now` },
    { label: "Priority recharge zones", value: number(data.active_zones), change: "High suitability", good: true, icon: Layers3, tone: "gold", sub: "Across 6 catchments" },
    { label: "Mean suitability", value: `${data.average_suitability}%`, change: "+4.2% vs. last run", good: true, icon: Sprout, tone: "sage", sub: "Model output · v2.4" },
    { label: "Model confidence", value: `${data.model_confidence}%`, change: "Within target", good: true, icon: Activity, tone: "blue", sub: "Validated field inputs" },
  ];
  return <main className="app-frame">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Waves size={21} strokeWidth={2.2}/></div><div><b>springvyra</b><span>WATERSHED INTELLIGENCE</span></div></div><div className="workspace-label">WORKSPACE <ChevronDown size={13}/></div><div className="workspace-card"><div className="workspace-icon">NG</div><div><b>North Garhwal</b><span>Uttarakhand, India</span></div><MoreHorizontal size={17}/></div><div className="nav-label">MONITOR</div><nav className="nav-list">{[{name:"Overview",icon:Activity},{name:"Spring network",icon:Droplets},{name:"Recharge zones",icon:Layers3},{name:"Field observations",icon:Leaf}].map(({name,icon:Icon})=><button key={name} className={`nav-item ${view===name?"selected":""}`} onClick={()=>setView(name)}><Icon size={17}/>{name}{name==="Spring network"&&<span className="nav-count">08</span>}</button>)}</nav><div className="nav-label tools-label">TOOLS</div><button className="nav-item"><MapPin size={17}/>Catchment explorer</button><button className="nav-item"><Cloud size={17}/>Rainfall & climate</button><div className="sidebar-spacer"/><div className="season-card"><div className="season-top"><span className="season-dot"/>MONSOON WATCH</div><b>Pre-monsoon</b><p>Recharge window opens in <strong>18 days</strong></p><div className="season-track"><span/></div><small>Seasonal readiness · 72%</small></div><div className="user-card"><div className="avatar">AK</div><div><b>Aditya Kumar</b><span>Watershed analyst</span></div><ChevronDown size={15}/></div></aside>
    <section className="main-column"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><i>/</i><b>{view}</b></div><div className="top-actions"><span className={`sync-state ${live?"is-live":""}`}><span/> {live?"Live connection":"Demo data"}</span><button className="icon-button" aria-label="Search"><Search size={17}/></button><button className="help-button"><CircleHelp size={16}/> Help centre</button><div className="top-avatar">AK</div></div></header>
    <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/>MONDAY, 29 SEPTEMBER 2026 <span className="eyebrow-bullet">·</span> POST-MONSOON REVIEW</div><h1>Good morning, Aditya <span className="wave">✳</span></h1><p>Here’s what’s happening across your watershed today.</p></div><div className="heading-actions"><button className="secondary-button"><SlidersHorizontal size={15}/> Customize</button><button className="primary-button"><Download size={15}/> Export report</button></div></div>
    <div className="stats-grid">{statCards.map(({label,value,change,good,icon:Icon,tone,sub})=><article className="stat-card" key={label}><div className="stat-head"><span>{label}</span><span className={`stat-icon ${tone}`}><Icon size={17}/></span></div><div className="stat-value">{value}</div><div className="stat-foot"><span className={`change ${good?"positive":""}`}>{good?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {change}</span><span className="stat-sub">{sub}</span></div><div className={`sparkline ${tone}`}><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/></div></article>)}</div>
    <div className="section-heading"><div><h2>Watershed overview</h2><p>Spring locations and recharge potential across North Garhwal</p></div><button className="period-button">Last 30 days <ChevronDown size={14}/></button></div>
    <section className="map-panel"><div className="map-toolbar"><div className="map-title"><span className="map-title-icon"><MapPin size={16}/></span><div><b>Spring & recharge map</b><small>North Garhwal · Uttarakhand</small></div><span className="map-live"><Radio size={12}/> LIVE</span></div><div className="map-tools"><button><Layers3 size={15}/> Layers <ChevronDown size={13}/></button><button><Menu size={15}/> Legend</button><button className="expand-button">⛶</button></div></div><div className="map-content"><MapView springs={data.springs}/><div className="map-legend"><b>MAP LEGEND</b><span><i className="legend-dot flowing"/>Flowing spring</span><span><i className="legend-dot watch"/>Seasonal / watch</span><span><i className="legend-zone"/>High recharge suitability</span></div><div className="map-scale"><span>0</span><i/><span>2 km</span></div></div><div className="map-summary"><div><Droplets size={15}/><span><b>{data.total_springs} springs</b> mapped</span></div><div><Layers3 size={15}/><span><b>{data.active_zones} priority zones</b> identified</span></div><span className="map-updated">Updated 4 min ago</span></div></section>
    <section className="inventory-section"><div className="inventory-heading"><div><h2>Spring inventory</h2><p>Latest field status from monitored sources</p></div><button className="text-button" onClick={()=>setView("Spring network")}>View all springs <span>↗</span></button></div><div className="table-wrap"><table><thead><tr><th>SPRING</th><th>TYPE</th><th>ELEVATION</th><th>DISCHARGE</th><th>WATER PH</th><th>STATUS</th><th/></tr></thead><tbody>{data.springs.slice(0,5).map((s,i)=><tr key={s.id}><td><div className="spring-cell"><span className={`spring-mini mini-${i%4}`}><Droplets size={15}/></span><span><b>{s.name}</b><small>{s.spring_code}</small></span></div></td><td><span className="type-pill">{s.spring_type}</span></td><td>{number(s.elevation)} <span className="unit">m</span></td><td><b>{s.discharge_rate.toFixed(2)}</b> <span className="unit">L/s</span></td><td>{s.water_quality_ph.toFixed(1)}</td><td><span className={`status-pill ${s.status.toLowerCase()}`}><i/>{s.status}</span></td><td><button className="row-menu" aria-label="More options"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></section>
    <footer><span>SpringVyra <b>·</b> Watershed intelligence for resilient mountain communities</span><span>Dashboard syncs every 30 sec <i/> <button>Data sources & methodology</button></span></footer></div></section>
  </main>;
}
