"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Activity, AlertTriangle, Database, Layers3, Plus, RefreshCw } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
type Readiness = { can_analyze: boolean; available_parameters: { parameter: string; source: string; acquisition_date: string | null; resolution_m: number | null; license: string | null; data_status: string }[]; missing_parameters: string[]; data_quality: string; message: string };

export function RechargeModule() {
  const [readiness, setReadiness] = useState<Readiness | null>(null); const [result, setResult] = useState("");
  useEffect(() => { fetch(`${API}/api/recharge/readiness`).then(r => r.ok ? r.json() : Promise.reject()).then(setReadiness).catch(() => setResult("Unable to connect to the analysis service. Check that the backend is running.")); }, []);
  async function analyze() { setResult(""); try { const r = await fetch(`${API}/api/recharge/analyze`, { method: "POST" }); const body = await r.json(); setResult(body.detail?.message || body.message || "Analysis is unavailable."); } catch { setResult("Unable to connect to the analysis service. Check that the backend is running."); } }
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Recharge suitability readiness</h2><p>Analysis is blocked until source data and a validated GIS pipeline are configured.</p></div><span className="status-pill monitoring">NOT RUN</span></div><div className="field-data-warning">Decision-support only. A future probable recharge zone must be field-validated and reviewed by an expert.</div>{readiness && <><div className="readiness-banner"><b>Analysis unavailable</b><span>{readiness.message}</span></div><h3>Required environmental inputs</h3><div className="parameter-list">{[...readiness.available_parameters.map(x=>({name:x.parameter,available:true,source:x.source,status:x.data_status})), ...readiness.missing_parameters.map(name=>({name,available:false,source:"",status:"MISSING"}))].map((item,i)=><div className="parameter-row" key={`${item.name}-${i}`}><span className={item.available?"parameter-ok":"parameter-missing"}>{item.available?"CATALOGED":"MISSING"}</span><b>{item.name}</b><small>{item.available?`${item.source} · ${item.status} metadata; files not connected`:"No source configured"}</small></div>)}</div><button className="field-submit" onClick={analyze}><RefreshCw size={14}/> Check analysis availability</button>{result&&<p className="field-form-message" role="status">{result}</p>}</>}</section>;
}

type Source = { id: number; dataset_name: string; source_name: string; source_url?: string; acquisition_date?: string; spatial_resolution_m?: number; license_name?: string; processing_method?: string; data_status: string };
export function DataSourcesModule() {
  const [rows,setRows]=useState<Source[]>([]); const [message,setMessage]=useState("");
  const load=()=>fetch(`${API}/api/data-sources`).then(r=>r.ok?r.json():Promise.reject()).then(setRows).catch(()=>setMessage("Unable to load data sources. Check that the backend is running."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={dataset_name:String(form.get("dataset_name")),source_name:String(form.get("source_name")),source_url:String(form.get("source_url")||"")||null,acquisition_date:String(form.get("acquisition_date")||"")||null,spatial_resolution_m:Number(form.get("spatial_resolution_m"))||null,license_name:String(form.get("license_name")||"")||null,processing_method:String(form.get("processing_method")||"")||null,data_status:"UNVERIFIED"};try{const r=await fetch(`${API}/api/data-sources`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save source metadata.");formElement.reset();setMessage("Source metadata saved as UNVERIFIED. This does not upload or process the dataset.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Dataset provenance</h2><p>Record source and quality metadata. Upload and spatial processing are not configured.</p></div><Database size={19}/></div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Dataset name<input name="dataset_name" required placeholder="DEM, geology, rainfall…" maxLength={120}/></label><label>Source / provider<input name="source_name" required maxLength={180}/></label><label>Acquisition date<input name="acquisition_date" type="date"/></label><label>Spatial resolution (m)<input name="spatial_resolution_m" type="number" min="0.001" step="any"/></label><label>License<input name="license_name" maxLength={180}/></label><label>Source URL<input name="source_url" type="url" maxLength={500}/></label></div><label>Processing method<textarea name="processing_method" rows={2}/></label><button className="field-submit"><Plus size={14}/> Save source metadata</button></form>{message&&<p className="field-form-message" role="status">{message}</p>}<div className="source-list">{rows.map(row=><article key={row.id}><b>{row.dataset_name}</b><span>{row.source_name} · {row.data_status}</span><small>{row.acquisition_date||"Date not supplied"} · {row.spatial_resolution_m?`${row.spatial_resolution_m} m` : "Resolution not supplied"} · {row.license_name||"License not supplied"}</small></article>)}{rows.length===0&&<p className="empty-state">No source metadata recorded yet.</p>}</div></section>;
}

type Candidate = { id:number; site_code:string; intervention_type:string; status:string; rationale?:string; risk_notes?:string; data_status:string };
export function InterventionModule() {
  const [rows,setRows]=useState<Candidate[]>([]); const [message,setMessage]=useState("");
  const load=()=>fetch(`${API}/api/interventions`).then(r=>r.ok?r.json():Promise.reject()).then(setRows).catch(()=>setMessage("Unable to load candidate records."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={site_code:String(form.get("site_code")),intervention_type:String(form.get("intervention_type")),latitude:Number(form.get("latitude")),longitude:Number(form.get("longitude")),rationale:String(form.get("rationale")||""),risk_notes:String(form.get("risk_notes")||""),data_status:"UNVERIFIED"};try{const r=await fetch(`${API}/api/interventions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save candidate record.");formElement.reset();setMessage("Stored as a candidate for field validation. This is not a construction recommendation.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Intervention candidates</h2><p>Manually record a candidate for field review; no automatic prioritization is active.</p></div><AlertTriangle size={19}/></div><div className="field-data-warning">Never treat a candidate record as approval to build. Confirm location, risks, suitability, and field conditions with qualified reviewers.</div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Site code<input name="site_code" required maxLength={32}/></label><label>Intervention type<select name="intervention_type"><option>Recharge pit</option><option>Recharge trench</option><option>Check dam</option><option>Percolation structure</option><option>Contour trench</option><option>Other</option></select></label><label>Latitude<input name="latitude" type="number" min="-90" max="90" step="any" required/></label><label>Longitude<input name="longitude" type="number" min="-180" max="180" step="any" required/></label></div><label>Reason for field review<textarea name="rationale" rows={2}/></label><label>Known risks / unknowns<textarea name="risk_notes" rows={2}/></label><button className="field-submit"><Plus size={14}/> Save candidate record</button></form>{message&&<p className="field-form-message" role="status">{message}</p>}<div className="source-list">{rows.map(row=><article key={row.id}><b>{row.site_code} · {row.intervention_type}</b><span>{row.status} · {row.data_status}</span><small>{row.rationale||"No rationale supplied."} {row.risk_notes||"Risk information not supplied."}</small></article>)}{rows.length===0&&<p className="empty-state">No candidate intervention records.</p>}</div></section>;
}

type Measurement = { id:number; spring_id:number; discharge:number|null; water_level:number|null; water_quality_ph:number|null; measured_at:string; observer?:string; data_status:string };
type SpringOption = { id:number; spring_code:string; name:string; data_status:string };
export function MonitoringModule() {
  const [measurements,setMeasurements]=useState<Measurement[]>([]);const [springs,setSprings]=useState<SpringOption[]>([]);const [message,setMessage]=useState("");
  const load=()=>Promise.all([fetch(`${API}/api/monitoring`),fetch(`${API}/api/springs`)]).then(async([m,s])=>{if(!m.ok||!s.ok)throw new Error();setMeasurements(await m.json());setSprings(await s.json());}).catch(()=>setMessage("Unable to load monitoring data. Check the API connection."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={spring_id:Number(form.get("spring_id")),discharge:form.get("discharge")?Number(form.get("discharge")):null,water_level:form.get("water_level")?Number(form.get("water_level")):null,water_quality_ph:form.get("water_quality_ph")?Number(form.get("water_quality_ph")):null,observer:String(form.get("observer")||""),notes:String(form.get("notes")||""),data_status:"FIELD"};try{const r=await fetch(`${API}/api/monitoring`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save measurement.");formElement.reset();setMessage("Measurement stored as FIELD data. It has not been independently validated.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Spring monitoring</h2><p>Store dated measurements; values are not independently verified by this form.</p></div><Activity size={19}/></div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Spring<select name="spring_id" required defaultValue=""><option value="" disabled>Select a spring</option>{springs.map(s=><option key={s.id} value={s.id}>{s.spring_code} · {s.name} · {s.data_status}</option>)}</select></label><label>Observer<input name="observer" maxLength={120}/></label><label>Discharge (L/s)<input name="discharge" type="number" min="0" step="any"/></label><label>Water level (m)<input name="water_level" type="number" step="any"/></label><label>Water pH<input name="water_quality_ph" type="number" min="0" max="14" step="any"/></label></div><label>Notes<textarea name="notes" rows={2}/></label><button className="field-submit" disabled={springs.length===0}><Plus size={14}/> Save measurement</button></form>{message&&<p className="field-form-message">{message}</p>}<div className="source-list">{measurements.map(m=><article key={m.id}><b>Spring record #{m.spring_id} · {m.data_status}</b><span>{m.measured_at?new Date(m.measured_at).toLocaleString():"Time not supplied"} · {m.observer||"Observer not supplied"}</span><small>{m.discharge==null?"Discharge not recorded":`${m.discharge} L/s`} · {m.water_level==null?"Water level not recorded":`${m.water_level} m`} · {m.water_quality_ph==null?"pH not recorded":`pH ${m.water_quality_ph}`}</small></article>)}{measurements.length===0&&<p className="empty-state">No measurement records available.</p>}</div></section>;
}

export function UnavailableModule({ title, endpoint, icon: Icon = Layers3 }: { title:string; endpoint:string; icon?: typeof Layers3 }) {
  const [message,setMessage]=useState("Loading status…");
  useEffect(()=>{fetch(`${API}${endpoint}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>setMessage(data.message||data.status||"No data available.")).catch(()=>setMessage("Unable to connect to the API."));},[endpoint]);
  return <section className="module-panel"><div className="module-panel-head"><div><h2>{title}</h2><p>This module reports source availability and limitations.</p></div><Icon size={19}/></div><div className="readiness-banner"><b>NOT AVAILABLE</b><span>{message}</span></div></section>;
}
