"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Activity, AlertTriangle, Database, Layers3, MapPin, Plus, RefreshCw } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
type Readiness = { can_analyze: boolean; available_parameters: { parameter: string; source: string; acquisition_date: string | null; resolution_m: number | null; license: string | null; data_status: string }[]; missing_parameters: string[]; data_quality: string; message: string };

export function RechargeModule() {
  const [analysis, setAnalysis] = useState<any>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${API}/api/recharge/analysis`).then(r => r.ok ? r.json() : Promise.reject()).then(setAnalysis).catch(() => setMessage("Unable to connect to the analysis service.")); }, []);
  return <section className="analysis-module"><div className="module-panel-head"><div><h2>Recharge suitability analysis</h2><p>Transparent prototype screening for the SIH26240 demonstration workflow.</p></div><span className="status-pill monitoring">PROTOTYPE OUTPUT</span></div><div className="field-data-warning"><b>Decision-support only.</b> Predictions require authoritative environmental data, field validation and expert review. No trained or validated ML model is active.</div>{message&&<p className="field-form-message">{message}</p>}{analysis&&<><div className="analysis-metrics"><article><span>Suitability score</span><b>{analysis.suitability_score}%</b><small>Prototype output</small></article><article><span>Model confidence</span><b>{analysis.confidence_score}%</b><small>Not scientific accuracy</small></article><article><span>Data completeness</span><b>{analysis.data_completeness}%</b><small>Missing source layers</small></article><article><span>Uncertainty</span><b>{analysis.uncertainty}</b><small>Field validation required</small></article></div><div className="analysis-grid"><section className="module-panel"><div className="module-panel-head"><div><h3>Contributing factors</h3><p>Configurable prototype weights, not measured importance.</p></div><Layers3 size={19}/></div><div className="factor-list">{analysis.factors.map((factor:{name:string;contribution:number})=><div className="factor-row" key={factor.name}><span>{factor.name}</span><div><i style={{width:`${factor.contribution}%`}}/></div><b>{factor.contribution}%</b></div>)}</div></section><section className="module-panel"><div className="module-panel-head"><div><h3>GIS layer readiness</h3><p>Unavailable layers remain explicitly visible.</p></div><Database size={19}/></div><div className="layer-list">{analysis.layers.map((layer:{name:string;status:string;available:boolean})=><div key={layer.name}><span className={layer.available?"parameter-ok":"parameter-missing"}>{layer.status}</span><b>{layer.name}</b></div>)}</div></section></div><section className="module-panel"><div className="module-panel-head"><div><h3>Suitability zones</h3><p>Scores are prototype/demo values and require field validation.</p></div><MapPin size={19}/></div><div className="zone-summary">{analysis.zones.map((zone:{zone_code:string;suitability_score:number;suitability_class:string;uncertainty:string})=><article key={zone.zone_code}><b>{zone.zone_code}</b><strong>{zone.suitability_score ?? "N/A"}%</strong><span>{zone.suitability_class} · {zone.uncertainty} uncertainty</span><small>FIELD VALIDATION REQUIRED</small></article>)}</div></section><section className="feedback-loop"><b>Model feedback loop</b><div>{analysis.feedback_loop.map((step:string,index:number)=><span key={step}>{index>0&&<i>↓</i>}{step}</span>)}</div><p>Validated field observations and subsequent spring measurements can evaluate and improve future model outputs. Automatic retraining is not active.</p></section></>}</section>;
}

type Source = { id: number; dataset_name: string; source_name: string; source_url?: string; acquisition_date?: string; spatial_resolution_m?: number; license_name?: string; processing_method?: string; data_status: string };
export function DataSourcesModule() {
  const [rows,setRows]=useState<Source[]>([]); const [message,setMessage]=useState("");
  const load=()=>fetch(`${API}/api/data-sources`).then(r=>r.ok?r.json():Promise.reject()).then(setRows).catch(()=>setMessage("Unable to load data sources. Check that the backend is running."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={dataset_name:String(form.get("dataset_name")),source_name:String(form.get("source_name")),source_url:String(form.get("source_url")||"")||null,acquisition_date:String(form.get("acquisition_date")||"")||null,spatial_resolution_m:Number(form.get("spatial_resolution_m"))||null,license_name:String(form.get("license_name")||"")||null,processing_method:String(form.get("processing_method")||"")||null,data_status:"UNVERIFIED"};try{const r=await fetch(`${API}/api/data-sources`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save source metadata.");formElement.reset();setMessage("Source metadata saved as UNVERIFIED. This does not upload or process the dataset.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Dataset provenance</h2><p>Record source and quality metadata. Upload and spatial processing are not configured.</p></div><Database size={19}/></div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Dataset name<input name="dataset_name" required placeholder="DEM, geology, rainfall…" maxLength={120}/></label><label>Source / provider<input name="source_name" required maxLength={180}/></label><label>Acquisition date<input name="acquisition_date" type="date"/></label><label>Spatial resolution (m)<input name="spatial_resolution_m" type="number" min="0.001" step="any"/></label><label>License<input name="license_name" maxLength={180}/></label><label>Source URL<input name="source_url" type="url" maxLength={500}/></label></div><label>Processing method<textarea name="processing_method" rows={2}/></label><button className="field-submit"><Plus size={14}/> Save source metadata</button></form>{message&&<p className="field-form-message" role="status">{message}</p>}<div className="source-list">{rows.map(row=><article key={row.id}><b>{row.dataset_name}</b><span>{row.source_name} · {row.data_status}</span><small>{row.acquisition_date||"Date not supplied"} · {row.spatial_resolution_m?`${row.spatial_resolution_m} m` : "Resolution not supplied"} · {row.license_name||"License not supplied"}</small></article>)}{rows.length===0&&<p className="empty-state">No source metadata recorded yet.</p>}</div></section>;
}

function PriorityTable() {
  const [items, setItems] = useState<{rank:number;site_code:string;suitability:number;risk_level:string;confidence:number;recommended_intervention:string;reason:string;validation_status:string}[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${API}/api/interventions/priorities`).then(r => r.ok ? r.json() : Promise.reject()).then(body => setItems(body.items || [])).catch(() => setMessage("Unable to load prototype priorities.")); }, []);
  return <section className="module-panel priority-panel"><div className="module-panel-head"><div><h2>Intervention prioritisation</h2><p>Prototype ranking for demonstration only. Every site requires field validation.</p></div><span className="status-pill monitoring">DEMO / PROTOTYPE</span></div>{message&&<p className="field-form-message">{message}</p>}<div className="priority-table-wrap"><table><thead><tr><th>RANK</th><th>SITE</th><th>SUITABILITY</th><th>RISK</th><th>CONFIDENCE</th><th>RECOMMENDATION</th><th>VALIDATION</th></tr></thead><tbody>{items.map(item=><tr key={item.site_code}><td><b>#{item.rank}</b></td><td><b>{item.site_code}</b><small>{item.reason}</small></td><td>{item.suitability}%</td><td><span className={`priority-risk ${item.risk_level.toLowerCase()}`}>{item.risk_level}</span></td><td>{item.confidence}%</td><td><b>{item.recommended_intervention}</b></td><td><span className="status-pill monitoring">PENDING</span></td></tr>)}</tbody></table></div></section>;
}

type Candidate = { id:number; site_code:string; intervention_type:string; status:string; rationale?:string; risk_notes?:string; data_status:string };
function CandidateEntryModule() {
  const [rows,setRows]=useState<Candidate[]>([]); const [message,setMessage]=useState("");
  const load=()=>fetch(`${API}/api/interventions`).then(r=>r.ok?r.json():Promise.reject()).then(setRows).catch(()=>setMessage("Unable to load candidate records."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={site_code:String(form.get("site_code")),intervention_type:String(form.get("intervention_type")),latitude:Number(form.get("latitude")),longitude:Number(form.get("longitude")),rationale:String(form.get("rationale")||""),risk_notes:String(form.get("risk_notes")||""),data_status:"UNVERIFIED"};try{const r=await fetch(`${API}/api/interventions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save candidate record.");formElement.reset();setMessage("Stored as a candidate for field validation. This is not a construction recommendation.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Intervention candidates</h2><p>Manually record a candidate for field review; no automatic prioritization is active.</p></div><AlertTriangle size={19}/></div><div className="field-data-warning">Never treat a candidate record as approval to build. Confirm location, risks, suitability, and field conditions with qualified reviewers.</div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Site code<input name="site_code" required maxLength={32}/></label><label>Intervention type<select name="intervention_type"><option>Recharge pit</option><option>Recharge trench</option><option>Check dam</option><option>Percolation structure</option><option>Contour trench</option><option>Other</option></select></label><label>Latitude<input name="latitude" type="number" min="-90" max="90" step="any" required/></label><label>Longitude<input name="longitude" type="number" min="-180" max="180" step="any" required/></label></div><label>Reason for field review<textarea name="rationale" rows={2}/></label><label>Known risks / unknowns<textarea name="risk_notes" rows={2}/></label><button className="field-submit"><Plus size={14}/> Save candidate record</button></form>{message&&<p className="field-form-message" role="status">{message}</p>}<div className="source-list">{rows.map(row=><article key={row.id}><b>{row.site_code} · {row.intervention_type}</b><span>{row.status} · {row.data_status}</span><small>{row.rationale||"No rationale supplied."} {row.risk_notes||"Risk information not supplied."}</small></article>)}{rows.length===0&&<p className="empty-state">No candidate intervention records.</p>}</div></section>;
}

export function InterventionModule() { return <div className="analysis-module"><PriorityTable/><CandidateEntryModule/></div>; }

function MonitoringTrends() {
  const [rows, setRows] = useState<{discharge:number|null;water_level:number|null;water_quality_ph:number|null;measured_at:string}[]>([]);
  useEffect(() => { fetch(`${API}/api/monitoring`).then(r => r.ok ? r.json() : Promise.reject()).then(setRows).catch(() => setRows([])); }, []);
  const latest = rows.slice(0, 8).reverse();
  const metric = (key: "discharge"|"water_level"|"water_quality_ph") => latest.map(row => row[key]).filter((value): value is number => value != null);
  const chart = (key: "discharge"|"water_level"|"water_quality_ph") => { const values = metric(key); const max = Math.max(...values, 1); return <div className="trend-chart">{latest.length ? latest.map((row,index) => <i key={`${key}-${index}`} style={{height:`${Math.max(((row[key] || 0) / max) * 100, 5)}%`}} title={`${row[key] ?? "Not recorded"}`}/>) : <span>No measurements yet</span>}</div>; };
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Historical monitoring trends</h2><p>Recent stored measurements; values remain subject to field review.</p></div><Activity size={19}/></div><div className="trend-grid"><article><b>Discharge (L/s)</b>{chart("discharge")}</article><article><b>Water level (m)</b>{chart("water_level")}</article><article><b>Water pH</b>{chart("water_quality_ph")}</article></div></section>;
}

function MonitoringProfile() {
  const [profile, setProfile] = useState<any>(null);
  useEffect(() => { Promise.all([fetch(`${API}/api/springs`), fetch(`${API}/api/monitoring`)]).then(async ([springs, measurements]) => { if (!springs.ok || !measurements.ok) throw new Error(); const springRows = await springs.json(); const measurementRows = await measurements.json(); const spring = springRows.find((row:{spring_code:string}) => row.spring_code === "NG-001") || springRows[0]; const latest = measurementRows.find((row:{spring_id:number}) => row.spring_id === spring?.id); setProfile(spring ? { ...spring, latest } : null); }).catch(() => setProfile(null)); }, []);
  if (!profile) return <section className="module-panel"><div className="empty-state">Spring profile is unavailable until spring records are connected.</div></section>;
  return <section className="module-panel spring-profile"><div className="module-panel-head"><div><h2>Spring profile</h2><p>{profile.name} · {profile.spring_code} · {profile.data_status}</p></div><span className="status-pill monitoring">{profile.status}</span></div><div className="profile-grid"><span><b>Coordinates</b>{profile.latitude.toFixed(4)}, {profile.longitude.toFixed(4)}</span><span><b>Elevation</b>{profile.elevation} m</span><span><b>Type</b>{profile.spring_type}</span><span><b>Latest discharge</b>{profile.latest?.discharge ?? "Not recorded"} L/s</span><span><b>Water level</b>{profile.latest?.water_level ?? "Not recorded"} m</span><span><b>pH</b>{profile.latest?.water_quality_ph ?? "Not recorded"}</span></div></section>;
}

type Measurement = { id:number; spring_id:number; discharge:number|null; water_level:number|null; water_quality_ph:number|null; measured_at:string; observer?:string; data_status:string };
type SpringOption = { id:number; spring_code:string; name:string; data_status:string };
function MeasurementEntryModule() {
  const [measurements,setMeasurements]=useState<Measurement[]>([]);const [springs,setSprings]=useState<SpringOption[]>([]);const [message,setMessage]=useState("");
  const load=()=>Promise.all([fetch(`${API}/api/monitoring`),fetch(`${API}/api/springs`)]).then(async([m,s])=>{if(!m.ok||!s.ok)throw new Error();setMeasurements(await m.json());setSprings(await s.json());}).catch(()=>setMessage("Unable to load monitoring data. Check the API connection."));
  useEffect(()=>{load();},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const payload={spring_id:Number(form.get("spring_id")),discharge:form.get("discharge")?Number(form.get("discharge")):null,water_level:form.get("water_level")?Number(form.get("water_level")):null,water_quality_ph:form.get("water_quality_ph")?Number(form.get("water_quality_ph")):null,observer:String(form.get("observer")||""),notes:String(form.get("notes")||""),data_status:"FIELD"};try{const r=await fetch(`${API}/api/monitoring`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save measurement.");formElement.reset();setMessage("Measurement stored as FIELD data. It has not been independently validated.");load();}catch(e){setMessage(e instanceof Error?e.message:"API unavailable.");}}
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Spring monitoring</h2><p>Store dated measurements; values are not independently verified by this form.</p></div><Activity size={19}/></div><form className="field-form source-form" onSubmit={save}><div className="field-form-grid"><label>Spring<select name="spring_id" required defaultValue=""><option value="" disabled>Select a spring</option>{springs.map(s=><option key={s.id} value={s.id}>{s.spring_code} · {s.name} · {s.data_status}</option>)}</select></label><label>Observer<input name="observer" maxLength={120}/></label><label>Discharge (L/s)<input name="discharge" type="number" min="0" step="any"/></label><label>Water level (m)<input name="water_level" type="number" step="any"/></label><label>Water pH<input name="water_quality_ph" type="number" min="0" max="14" step="any"/></label></div><label>Notes<textarea name="notes" rows={2}/></label><button className="field-submit" disabled={springs.length===0}><Plus size={14}/> Save measurement</button></form>{message&&<p className="field-form-message">{message}</p>}<div className="source-list">{measurements.map(m=><article key={m.id}><b>Spring record #{m.spring_id} · {m.data_status}</b><span>{m.measured_at?new Date(m.measured_at).toLocaleString():"Time not supplied"} · {m.observer||"Observer not supplied"}</span><small>{m.discharge==null?"Discharge not recorded":`${m.discharge} L/s`} · {m.water_level==null?"Water level not recorded":`${m.water_level} m`} · {m.water_quality_ph==null?"pH not recorded":`pH ${m.water_quality_ph}`}</small></article>)}{measurements.length===0&&<p className="empty-state">No measurement records available.</p>}</div></section>;
}

export function MonitoringModule() { return <div className="analysis-module"><MonitoringProfile/><MonitoringTrends/><MeasurementEntryModule/></div>; }

export function UnavailableModule({ title, endpoint, icon: Icon = Layers3 }: { title:string; endpoint:string; icon?: typeof Layers3 }) {
  const [status,setStatus]=useState("LOADING"); const [message,setMessage]=useState("Loading status…"); const [items,setItems]=useState<any[]>([]);
  useEffect(()=>{fetch(`${API}${endpoint}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setStatus(data.status||"AVAILABLE");setMessage(data.message||data.disclaimer||"No data available.");setItems(data.items||[]);}).catch(()=>{setStatus("UNAVAILABLE");setMessage("Unable to connect to the API.");});},[endpoint]);
  return <section className="module-panel"><div className="module-panel-head"><div><h2>{title}</h2><p>This module reports source availability and limitations.</p></div><Icon size={19}/></div><div className="readiness-banner"><b>{status}</b><span>{message}</span></div>{items.length>0&&<div className="risk-list">{items.map(item=><article key={item.site_code}><div><b>{item.site_code}</b><span>{item.overall}</span></div><p>Slope: {item.slope_risk} · Landslide: {item.landslide_risk} · Flood: {item.flood_risk} · Geology: {item.geological_risk}</p><small>{item.reason}</small></article>)}</div>}</section>;
}

export function ReportModule() {
  const [report, setReport] = useState<any>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${API}/api/reports/summary`).then(r => r.ok ? r.json() : Promise.reject()).then(setReport).catch(() => setMessage("Unable to load the assessment report.")); }, []);
  function download() { if (!report) return; const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `springvyra-assessment-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); }
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Watershed assessment report</h2><p>Structured prototype report for review and handoff.</p></div><FileTextIcon/></div>{message&&<p className="field-form-message">{message}</p>}{report&&<><div className="report-summary"><article><span>Study area</span><b>{report.study_area}</b></article><article><span>Springs</span><b>{report.dashboard.total_springs}</b></article><article><span>Priority sites</span><b>{report.priority_interventions.length}</b></article><article><span>Validation</span><b>{report.validation_status}</b></article></div><div className="field-data-warning"><b>{report.disclaimer}</b></div><h3>Data limitations</h3><ul className="report-list">{report.limitations.map((item:string)=><li key={item}>{item}</li>)}</ul><button className="field-submit" onClick={download}><DownloadIcon/> Download JSON report</button></>}</section>;
}

function FileTextIcon() { return <span aria-hidden="true">▤</span>; }
function DownloadIcon() { return <span aria-hidden="true">↓</span>; }
