"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";

type Spring = { id: number; spring_code: string; name: string; spring_type: string; latitude: number; longitude: number; elevation: number; discharge_rate: number; water_quality_ph: number; status: string; catchment?: string | null; description?: string | null; data_status: string };
type FormValues = Omit<Spring, "id" | "data_status">;
const blank: FormValues = { spring_code: "", name: "", spring_type: "", latitude: 0, longitude: 0, elevation: 0, discharge_rate: 0, water_quality_ph: 7, status: "unknown", catchment: "", description: "" };
const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

export function SpringManager() {
  const [rows, setRows] = useState<Spring[]>([]); const [form, setForm] = useState<FormValues>(blank); const [editing, setEditing] = useState<number | null>(null); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch(`${API}/api/springs`, { cache: "no-store" }); if (!r.ok) throw new Error("Spring records are unavailable."); setRows(await r.json()); } catch (e) { setMessage(e instanceof Error ? e.message : "API unavailable."); } }, []);
  useEffect(() => { load(); }, [load]);
  function startNew() { setEditing(null); setForm(blank); setShowForm(true); setMessage(""); }
  function startEdit(row: Spring) { const { id, data_status, ...values } = row; setEditing(id); setForm({ ...values, catchment: values.catchment || "", description: values.description || "" }); setShowForm(true); setMessage(`Editing ${row.spring_code} · ${data_status}`); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const r = await fetch(`${API}/api/springs${editing ? `/${editing}` : ""}`, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, latitude: Number(form.latitude), longitude: Number(form.longitude), elevation: Number(form.elevation), discharge_rate: Number(form.discharge_rate), water_quality_ph: Number(form.water_quality_ph), data_status: editing ? rows.find(x => x.id === editing)?.data_status || "UNVERIFIED" : "UNVERIFIED" }) }); if (!r.ok) { const body = await r.json(); throw new Error(typeof body.detail === "string" ? body.detail : "Could not save the spring record."); } setShowForm(false); await load(); setMessage(editing ? "Spring record updated." : "Spring record created as UNVERIFIED."); } catch (e) { setMessage(e instanceof Error ? e.message : "API unavailable."); } finally { setBusy(false); } }
  async function remove(row: Spring) { if (!window.confirm(`Delete spring record ${row.spring_code}? Associated field observations will also be deleted.`)) return; try { const r = await fetch(`${API}/api/springs/${row.id}`, { method: "DELETE" }); if (!r.ok) throw new Error("Could not delete spring record."); await load(); setMessage(`Deleted ${row.spring_code}.`); } catch (e) { setMessage(e instanceof Error ? e.message : "API unavailable."); } }
  return <section className="module-panel"><div className="module-panel-head"><div><h2>Spring records</h2><p>Create, review, or update stored spring locations. New records default to UNVERIFIED.</p></div><button className="field-submit" onClick={startNew}><Plus size={15}/> Add spring</button></div>{message && <p className="field-form-message" role="status">{message}</p>}{showForm && <form className="field-form spring-record-form" onSubmit={save}><div className="field-form-grid">{([["spring_code","Spring code"],["name","Name"],["spring_type","Spring type"],["elevation","Elevation (m)"],["latitude","Latitude"],["longitude","Longitude"],["discharge_rate","Discharge (L/s)"],["water_quality_ph","Water pH"],["status","Status"],["catchment","Catchment"]] as const).map(([key,label])=><label key={key}>{label}<input required={key!="catchment"} value={form[key] ?? ""} type={key === "elevation" || key === "latitude" || key === "longitude" || key === "discharge_rate" || key === "water_quality_ph" ? "number" : "text"} step="any" onChange={e=>setForm({ ...form, [key]: e.target.value } as FormValues)}/></label>)}</div><label>Description<textarea rows={2} value={form.description ?? ""} onChange={e=>setForm({ ...form, description: e.target.value })}/></label><div className="field-form-actions"><button type="submit" className="field-submit" disabled={busy}>{busy ? "Saving…" : editing ? "Save changes" : "Create record"}</button><button type="button" className="gps-button" onClick={()=>{setShowForm(false);setEditing(null);}}>Cancel <X size={14}/></button></div></form>}<div className="table-wrap"><table><thead><tr><th>SPRING</th><th>TYPE</th><th>COORDINATES</th><th>ELEVATION</th><th>STATUS</th><th>DATA SOURCE</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.name}</b><small className="spring-code-cell">{row.spring_code}</small></td><td>{row.spring_type}</td><td>{row.latitude.toFixed(5)}, {row.longitude.toFixed(5)}</td><td>{row.elevation} m</td><td>{row.status}</td><td><span className="type-pill">{row.data_status}</span></td><td><div className="record-actions"><button aria-label={`Edit ${row.spring_code}`} onClick={()=>startEdit(row)}><Pencil size={14}/></button><button aria-label={`Delete ${row.spring_code}`} onClick={()=>remove(row)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{rows.length === 0 && <p className="empty-state">No spring records loaded. Check the API connection or create a record.</p>}</div></section>;
}
